### ISSUE TITLE
uiSubtitleOverlay.html subtitles start to show only when you seek.

### ISSUE THREAD

**Issue by mhosman** [bitmovin/bitmovin-player-web-samples#26]

**Comment by SInCE** [comment]
Hi Mhosman,

While some time did pass by since this issue was open, the example does work by now already as expected ✅  For future requests or reports about problems with an example, please see the [Support Section](https://github.com/bitmovin/bitmovin-player-web-samples#support) how you can reach out to us going forward. Thank you very much for your understanding!
